Add error message in case of non-zero exit code

diff --git a/templates/s3_bucket.sh.j2 b/templates/s3_bucket.sh.j2
--- a/templates/s3_bucket.sh.j2
+++ b/templates/s3_bucket.sh.j2
@@ -17,6 +17,10 @@ finish() {
 
   rm -rf ${DEST_FILE}
 
+  if [ ${result} -ne 0 ]; then
+    echo "Error: non-zero exit code $result" 1>&2
+  fi
+
   exit ${result}
 }
 
